name: kind-cluster

on:
  push: 
    branches: master

jobs:  
    runs on: ubuntu-latest

steps: 
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v2
      with:
        docker-version: '25.0.3'
    - name: Install Kind
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.12.0/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin

    - name: Create Kind Cluster
      run: kind create cluster

    - name: Configure Kubeconfig
      run: kubectl cluster-info --context kind-kind
